# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-06 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20160805_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.CharField(default='ABC', max_length=120, unique=True),
        ),
    ]
